/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 10 07:52:29 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Book;
import ir.ramtung.impl2.Magazine;
import ir.ramtung.impl2.Reference;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Document_ESTest extends Document_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Book book0 = new Book((String) null, 0);
      book0.getTitle();
      assertEquals(0, book0.getCopies());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Magazine magazine0 = new Magazine("", 484, 2498, 0);
      String string0 = magazine0.getTitle();
      assertEquals(0, magazine0.getCopies());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Book book0 = new Book("", 1390);
      book0.day = 0;
      int int0 = book0.getDay();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Reference reference0 = new Reference("&(dw5K^<OEt-", (-1712));
      reference0.day = (-106);
      int int0 = reference0.getDay();
      assertEquals((-106), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Book book0 = new Book("G6TluDu0>!hkW=!{n>", 0);
      int int0 = book0.getCopies();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Book book0 = new Book("J>\u0004IS7UL!", 0);
      book0.barrowBook();
      int int0 = book0.getCopies();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Book book0 = new Book("6s##id~5D", (-505));
      book0.calculatePenalty(0);
      assertEquals((-505), book0.getCopies());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Magazine magazine0 = new Magazine("~", 31, 31, 31);
      int int0 = magazine0.getCopies();
      assertEquals(31, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Magazine magazine0 = new Magazine("~", 31, 31, 31);
      magazine0.returnBook();
      assertEquals(32, magazine0.getCopies());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Magazine magazine0 = new Magazine("~", 31, 31, 31);
      String string0 = magazine0.getTitle();
      assertEquals(31, magazine0.getCopies());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Magazine magazine0 = new Magazine("~", 31, 31, 31);
      int int0 = magazine0.getDay();
      assertEquals(2, int0);
      assertEquals(31, magazine0.getCopies());
  }
}
