/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 10 07:49:29 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("GkcokEZ}", 1390, (-1582), 1912);
      int int0 = magazine0.calculatePenalty(3270);
      assertEquals(2, magazine0.getDay());
      assertEquals(3000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine((String) null, 584, 584, 584);
      int int0 = magazine0.calculatePenalty(584);
      assertEquals(2000, int0);
      assertEquals(2, magazine0.getDay());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = new Magazine("`vjX)", 3254, 3254, 3254);
      int int0 = magazine0.calculatePenalty(3254);
      assertEquals(2, magazine0.getDay());
      assertEquals(3000, int0);
  }
}
