/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 10 09:43:54 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Member;
import ir.ramtung.impl1.Professor;
import ir.ramtung.impl1.Student;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Member_ESTest extends Member_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Professor professor0 = new Professor("\"#_k_B&]Jz/3V");
      Professor professor1 = new Professor((String) null);
      boolean boolean0 = professor0.sameAs(professor1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Professor professor0 = new Professor((String) null);
      professor0.name = "J!ft'|@";
      professor0.name = "";
      boolean boolean0 = professor0.isNamed("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Professor professor0 = new Professor("\"#_k_B&]Jz/3V");
      boolean boolean0 = professor0.isNamed("Empty student ID is not allowed");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Professor professor0 = new Professor("\"#_k_B&]Jz/3V");
      professor0.prevPenalty = (-747);
      professor0.prevPenalty = 2206;
      int int0 = professor0.getPrevPenalty();
      assertEquals(2206, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Professor professor0 = new Professor("\"#_k_B&]Jz/3V");
      professor0.prevPenalty = (-747);
      int int0 = professor0.getPrevPenalty();
      assertEquals((-747), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Professor professor0 = new Professor("^A9V4");
      // Undeclared exception!
      try { 
        professor0.sameAs((Member) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ir.ramtung.impl1.Member", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Student student0 = null;
      try {
        student0 = new Student("yy;YxGaFAA{c\"ljfW", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Empty member name not allowed
         //
         verifyException("ir.ramtung.impl1.Member", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Professor professor0 = new Professor("K)%vfp?C?&,e(");
      professor0.penalize((-1876));
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Professor professor0 = new Professor("\"#_k_B&]Jz/3V");
      int int0 = professor0.getPrevPenalty();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Professor professor0 = new Professor("K)%vfp?C?&,e(");
      boolean boolean0 = professor0.sameAs(professor0);
      assertTrue(boolean0);
  }
}
