/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 10 09:46:05 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl2.Book;
import ir.ramtung.impl2.Document;
import ir.ramtung.impl2.Prof;
import ir.ramtung.impl2.Reference;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Prof_ESTest extends Prof_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Prof prof0 = new Prof("ZKo_*NUE34=1:zy");
      LinkedList<Document> linkedList0 = new LinkedList<Document>();
      Book book0 = new Book("ZKo_*NUE34=1:zy", 5);
      Reference reference0 = new Reference("ZKo_*NUE34=1:zy", (-135));
      linkedList0.add((Document) reference0);
      linkedList0.add((Document) book0);
      prof0.docsBorrow = (List<Document>) linkedList0;
      linkedList0.offerFirst(book0);
      prof0.borrow(reference0);
      assertTrue(prof0.canBorrow());
      
      linkedList0.addFirst((Document) null);
      prof0.borrow(book0);
      boolean boolean0 = prof0.canBorrow();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Prof prof0 = new Prof("n");
      List<Document> list0 = prof0.docsBorrow;
      prof0.docsBorrow = list0;
      prof0.docsBorrow = null;
      // Undeclared exception!
      try { 
        prof0.canBorrow();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ir.ramtung.impl2.Prof", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Prof prof0 = new Prof("ZKo_*NUE34=1:zy");
      LinkedList<Document> linkedList0 = new LinkedList<Document>();
      Book book0 = new Book("ZKo_*NUE34=1:zy", 5);
      Reference reference0 = new Reference("ZKo_*NUE34=1:zy", (-135));
      linkedList0.add((Document) reference0);
      linkedList0.add((Document) book0);
      prof0.docsBorrow = (List<Document>) linkedList0;
      prof0.borrow(reference0);
      assertTrue(prof0.canBorrow());
      
      linkedList0.addFirst((Document) null);
      prof0.borrow(book0);
      boolean boolean0 = prof0.canBorrow();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Prof prof0 = new Prof("");
      boolean boolean0 = prof0.canBorrow();
      assertTrue(boolean0);
  }
}
