/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 10 09:45:49 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("", 1390, 1438, 1438);
      int int0 = magazine0.calculatePenalty(1390);
      assertEquals(3000, int0);
      assertEquals(2, magazine0.getDay());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine("M*Z~ jU5", 1547, 1547, 1547);
      int int0 = magazine0.calculatePenalty(1547);
      assertEquals(3000, int0);
      assertEquals(2, magazine0.getDay());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = new Magazine("<DP_S,FSR{", (-24), (-24), (-24));
      int int0 = magazine0.calculatePenalty((-24));
      assertEquals(2000, int0);
      assertEquals(2, magazine0.getDay());
  }
}
