/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 10 07:40:32 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Book;
import ir.ramtung.impl1.Document;
import ir.ramtung.impl1.Loan;
import ir.ramtung.impl1.Magazine;
import ir.ramtung.impl1.Member;
import ir.ramtung.impl1.Professor;
import ir.ramtung.impl1.Reference;
import ir.ramtung.impl1.Student;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Loan_ESTest extends Loan_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Professor professor0 = new Professor("<zUW%Awv=^z");
      Magazine magazine0 = new Magazine("<zUW%Awv=^z", 1256, 1256);
      Loan loan0 = new Loan(professor0, magazine0, 1256);
      loan0.dueDate = 1256;
      int int0 = loan0.getPenalty(1256);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Professor professor0 = new Professor("Invalid argument to loan constructor");
      Book book0 = new Book("Invalid argument to loan constructor");
      Loan loan0 = new Loan(professor0, book0, 3685);
      loan0.dueDate = (-2841);
      loan0.return_((-2841));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Professor professor0 = new Professor("Cannot extend on the same day borrowed");
      Book book0 = new Book("Cannot extend on the same day borrowed");
      Loan loan0 = new Loan(professor0, book0, 56000);
      loan0.dueDate = 14000;
      loan0.extend(14000);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Professor professor0 = new Professor("Cannot extend on the same day borrowed");
      Book book0 = new Book("Cannot extend on the same day borrowed");
      Loan loan0 = new Loan(professor0, book0, 56000);
      loan0.dueDate = 14000;
      int int0 = loan0.getPenalty(56000);
      assertEquals(209951000, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Student student0 = new Student("ir.ramtung.impl1.Book", "ir.ramtung.impl1.Book");
      Reference reference0 = new Reference("Empty student ID is not allowed");
      Loan loan0 = new Loan(student0, reference0, 0);
      int int0 = loan0.getPenalty(2217000);
      assertEquals((-1799989888), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Professor professor0 = new Professor("Empty member name not allowed");
      Book book0 = new Book("&mi}a)*]ZQel.8D`cV");
      Loan loan0 = new Loan(professor0, book0, 5000);
      loan0.extend(0);
      loan0.extend(0);
      try { 
        loan0.extend(1335);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Already extended twice
         //
         verifyException("ir.ramtung.impl1.Loan", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Professor professor0 = new Professor("<zUW%Awv=^z");
      Magazine magazine0 = new Magazine("<zUW%Awv=^z", 1256, 1256);
      Loan loan0 = new Loan(professor0, magazine0, 1256);
      int int0 = loan0.getPenalty(1256);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Professor professor0 = new Professor("<zUW%Awv=^z");
      Magazine magazine0 = new Magazine("<zUW%Awv=^z", 1256, 1256);
      Loan loan0 = new Loan(professor0, magazine0, 1256);
      loan0.dueDate = 1256;
      loan0.dueDate = 0;
      loan0.return_(1256);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Student student0 = new Student("ir.ramtung.impl1.Book", "ir.ramtung.impl1.Book");
      Reference reference0 = new Reference("Empty student ID is not allowed");
      Loan loan0 = new Loan(student0, reference0, 0);
      loan0.return_((-2337));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Student student0 = new Student("3'flv/1!Q &M", "3'flv/1!Q &M");
      Book book0 = new Book("3'flv/1!Q &M");
      Loan loan0 = new Loan(student0, book0, 1277);
      try { 
        loan0.extend(1297);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot extend a late loan
         //
         verifyException("ir.ramtung.impl1.Loan", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Professor professor0 = new Professor("<zUW%Awv=^z");
      Magazine magazine0 = new Magazine("<zUW%Awv=^z", 1256, 1256);
      Loan loan0 = new Loan(professor0, magazine0, 1256);
      try { 
        loan0.extend(1256);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot extend on the same day borrowed
         //
         verifyException("ir.ramtung.impl1.Loan", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Professor professor0 = new Professor("<zUW%Awv=^z");
      Magazine magazine0 = new Magazine("<zUW%Awv=^z", 1256, 1256);
      Loan loan0 = new Loan(professor0, magazine0, 1256);
      boolean boolean0 = loan0.isBy(professor0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Professor professor0 = new Professor("<zUW%Awv=^z");
      Magazine magazine0 = new Magazine("<zUW%Awv=^z", 1256, 1256);
      Loan loan0 = new Loan(professor0, magazine0, 1256);
      boolean boolean0 = loan0.isBy((Member) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Professor professor0 = new Professor("<zUW%Awv=^z");
      Magazine magazine0 = new Magazine("<zUW%Awv=^z", 1256, 1256);
      Loan loan0 = new Loan(professor0, magazine0, 1256);
      boolean boolean0 = loan0.isFor(magazine0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Professor professor0 = new Professor("<zUW%Awv=^z");
      Magazine magazine0 = new Magazine("<zUW%Awv=^z", 1256, 1256);
      Loan loan0 = new Loan(professor0, magazine0, 1256);
      Reference reference0 = new Reference("<zUW%Awv=^z");
      boolean boolean0 = loan0.isFor(reference0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Student student0 = new Student("Cannot extend a late loan", "Cannot extend a late loan");
      Loan loan0 = null;
      try {
        loan0 = new Loan(student0, (Document) null, (-552));
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Invalid argument to loan constructor
         //
         verifyException("ir.ramtung.impl1.Loan", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Loan loan0 = null;
      try {
        loan0 = new Loan((Member) null, (Document) null, (-868));
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Invalid argument to loan constructor
         //
         verifyException("ir.ramtung.impl1.Loan", e);
      }
  }
}
