/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 10 07:43:30 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("Magazine with zero or negative number", 1390, 1390);
      int int0 = magazine0.penaltyFor(1);
      assertEquals(3000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine("+q1PoFWu,M2W>P", 1667, 1667);
      int int0 = magazine0.penaltyFor(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = new Magazine("ir.ramtung.impl1.Magazine", 1, 1);
      int int0 = magazine0.penaltyFor((-1519));
      assertEquals((-3038000), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Magazine magazine0 = new Magazine("jB", 34, 34);
      magazine0.year = 2567;
      int int0 = magazine0.penaltyFor(34);
      assertEquals(102000, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("P6Ry)6", 2000, 0);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative number
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("1~lM~ r10E=q", (-1106), (-1106));
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative publication year
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Magazine magazine0 = new Magazine("jB", 34, 34);
      int int0 = magazine0.loanDuration();
      assertEquals(2, int0);
  }
}
